export { ERROR_CODES } from './errors'
export type { ErrorCode } from './errors'

export {
  MAX_FILE_SIZE_BYTES,
  RETENTION_DAYS,
  EXPIRY_WARNING_DAYS,
  DEEPSEEK_TIMEOUT_MS,
  BCRYPT_SALT_ROUNDS,
  MAGIC_LINK_EXPIRY_MINUTES,
  SESSION_MAX_AGE_SECONDS,
  SIGNED_URL_EXPIRY_SECONDS,
  CLOUDINARY_FOLDER,
  ACCEPTED_MIME_TYPES,
  ACCEPTED_EXTENSIONS,
  LEGAL_DISCLAIMER,
} from './document'
